name: idyllic
version: 0.1.0
summary: API Testing Desktop Software
description: Support Json and protobuf response content-type

confinement: strict
base: core18
grade: devel

slots:
  dbus-idyllic: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.super_cool_app # adjust accordingly to your app name and
    
apps:
  idyllic:
    command: idyllic
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-idyllic
parts:
  idyllic:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
